packages:
  - packages/**

autoInstallPeers: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@nl-design-system-community/ma-design-tokens'

patchedDependencies:
  '@utrecht/figure-css@1.5.1': patches/@utrecht__figure-css@1.5.1.patch

savePrefix: ''
