packages:
  - packages/**

autoInstallPeers: false

# Configure pnpm so it only installs package versions that have been published on the npm registry for at least 24 hours
# (1440 minutes). This helps mitigate the risk of supply chain attacks by avoiding newly published, potentially
# malicious versions. Keep this in sync with npm-check-updates's `cooldown` configuration.
minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@nl-design-system-community/ma-design-tokens'

patchedDependencies:
  '@utrecht/figure-css@1.5.1': patches/@utrecht__figure-css@1.5.1.patch

savePrefix: ''
