import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gebruikersonderzoekSidebar: [
    {
      collapsible: false,
      items: [
        {
          dirName: 'onderzoek-bekijken',
          type: 'autogenerated',
        },
      ],
      label: 'Onderzoek bekijken',
      link: {
        slug: '/onderzoek-bekijken/',
        title: 'Overzicht',
        type: 'generated-index',
      },
      type: 'category',
    },
  ],
  meedoenSidebar: [{ dirName: 'onderzoek-delen', type: 'autogenerated' }],
  vragenSidebar: [{ dirName: 'vragen', type: 'autogenerated' }],
};

export default sidebars;
