import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gebruikersonderzoekSidebar: [
    {
      type: 'category',
      label: 'Onderzoek bekijken',
      link: {
        type: 'generated-index',
        title: 'Overzicht',
        slug: '/onderzoek-bekijken/',
      },
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'onderzoek-bekijken',
        },
      ],
    },
  ],
  meedoenSidebar: [{ type: 'autogenerated', dirName: 'onderzoek-delen' }],
  vragenSidebar: [{ type: 'autogenerated', dirName: 'vragen' }],
};

export default sidebars;
