name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: gh-pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install pnpm package manager
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set up Node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies specified in package.json
        run: |
          pnpm install --frozen-lockfile
          pnpm ls --recursive

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install pnpm package manager
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set up Node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies specified in package.json
        run: pnpm install --frozen-lockfile

      - name: Run the lint script in package.json scripts
        run: pnpm run --if-present lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Configure Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Install pnpm package manager
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Set up Node.js version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies specified in package.json
        run: pnpm install --frozen-lockfile

      - name: Run the build script in package.json scripts
        env:
          BASE_URL: "/gebruikersonderzoeken/"
        run: pnpm run --if-present build

      - name: Upload the results from the build step
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: build/

  publish-website:
    name: Publish website
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      - name: Deploy
        id: deploy-pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
